spring:
  application:
    name: Workload-ms

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  mongodb:
    uri: mongodb://localhost:27017/workload_db

server:
  port: 9090

jwt:
  secret: K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

activemq:
  queue:
    workload: workload.queue
